### ISSUE TITLE
filtool -z syntax

### ISSUE THREAD

**Issue by kmjc** [ypmen/PulsarX#3]
Hi

This seems like a ridiculously simple question, but what is the correct syntax for using different zapping methods with filtool?

I'm attempting to try out PulsarX via the docker image. I would like to be able to run multiple RFI zapping methods sequentially like for Fig 2 of the paper.

But I first ran into a more fundamental problem, no matter what -z options I use with filtool I'm getting the exact same mask.

I've used 
`filtool -v --mask -z zdot`
`filtool -v --mask -z mask 4 8`
`filtool -v --mask -z kadaneF 4 8`
and even
`filtool -v --mask -z zap 400 500`
and they all write the exact same mask to the _mask.fil file.

What am I doing wrong here?

**Comment by ypmen** [comment]
Hi @kmjc . This is a bug that the code didn't add manually zapped channels that I have fixed in the latest version. Please update XLibs and PulsarX, or use the latest docker image. Thanks for reporting the issue!

**Comment by kmjc** [comment]
amazing, thanks!
